### ISSUE TITLE
啥意思更新

### ISSUE THREAD

**Issue by odjsm** [MasonDye/CC-Attack-Rewrite#1]
啥时候更新

**Comment by MasonDye** [comment]
下一次更新什么还没决定，您提提建议？
The next update hasn't been decided yet. Do you have any suggestions?

**Comment by odjsm** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by odjsm** [comment]
> 下一次更新什么尚未决定，您提提建议？ 下一次更新尚未决定。你有什么建议吗？

支持http代理

**Comment by MasonDye** [comment]
现在是支持的呢，您看一下README.MD，只是对格式有要求。
It is supported now; just take a look at the README.MD. There are just some formatting requirements.

ip pool (eg. ip-list.txt)
<pre><code>http://address:port
http://address:port
http://address:port
......</code></pre>

**Comment by odjsm** [comment]
能把前面的http://这个去除吗

**Comment by odjsm** [comment]
你这属于第几层

**Comment by MasonDye** [comment]
下一个版本会去除 ``http://`` ，您提到的``“你这属于第几层”``，代码中并没有使用多层代理，但是在协议栈中属于应用层代理。

The next version will remove "http://". Regarding your mention of "What layer does this belong to," the code does not use multiple layers of proxies, but it falls under the category of an application layer proxy in the protocol stack.

**Comment by odjsm** [comment]
攻击不是有l4和7吗，你这是?

**Comment by MasonDye** [comment]
属于七层攻击
this is L7.

**Comment by MasonDye** [comment]
Close
